import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import TRPCProvider from "@/providers/tRPCProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ClientOnly from "@/providers/ClientOnly";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar/navbar";
import MainPage from "@/components/main/main-page";
import getCurrentUser from "@/auth/getCurrentUser";
import { Root } from "@radix-ui/react-toast";

const font = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayoutProps> = async ({ children }) => {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={cn(
          font.className,
          "antialiased min-h-[calc(100vh-5rem)] bg-background"
        )}
      >
        <TRPCProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ClientOnly>
              <Navbar />
              <MainPage user={user} />
              {children}
            </ClientOnly>
            <Toaster />
            {/* <Footer /> */}
          </ThemeProvider>
        </TRPCProvider>
      </body>
    </html>
  );
};

export default RootLayout;
