import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import TRPCProvider from "@/providers/tRPCProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ClientOnly from "@/providers/ClientOnly";
import { Toaster } from "@/components/ui/toaster";
import ThemeToggle from "@/components/ui/themeToggle";
import Navbar from "@/components/navbar/navbar";

const font = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          font.className,
          "antialiased min-h-[calc(100vh-5rem)] bg-background"
        )}
      >
        <TRPCProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ClientOnly>
              <Navbar />
            </ClientOnly>{" "}
            {children}
            <Toaster />
            {/* <Footer /> */}
          </ThemeProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
